### PR TITLE
Add Polish language

### PR DESCRIPTION
**Pull request by DEVELPL**

### CODE REVIEW

**Comment by DEVELPL** [comment]
Sorry for mistakes but I'm new in git "world"

**Comment by jim-parry** [comment]
Once you get used to it, you will wonder how you lived without it :)
Are you willing to be the "maintainer" for the Polish translations moving forward?

**Comment by jim-parry** [comment]
ps - You won't show as an official "contributor" unless commits are GPG-signed.

**Comment by DEVELPL** [comment]
Okay, my name is Maciej Jasiewicz

**Comment by jim-parry** [comment]
Putting you in the maintainer's list makes you official "maintainer".
And you have contributed, but you won't show in the contributor count, according to github, until fitire commits are signed. It can get confusing :-/

**Comment by DEVELPL** [comment]
How to sign it?

Signed-off-by: Maciej Jasiewicz, DEVELPL<kontakt.devel@gmail.com>
Is this okay?

**Comment by jim-parry** [comment]
That is only "signed off", and easily spoofed. GPG-signing refers to https://help.github.com/articles/managing-commit-signature-verification
We talk about it in the main repo ... https://github.com/bcit-ci/CodeIgniter4/blob/develop/contributing/signing.rst

**Comment by michalsn** [comment]
@DEVELPL Just send a PR with changes to the README and add a reference to this post in the description of the PR.

**Pull request merged**
